# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DR-Ym2ug1bT2bI3O59J7Q6Wm91viacuK

it is my first colab code. today i am going to tokenize  the input sentence.
"""

#import
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
 #input the text
Sentence = ['I am Madan Parajuli','I am software engineer',
             'I have good skill in python','I am Nepali',
             'Madan loves to code']
print(Sentence)

tokenizer = Tokenizer(num_words= 100, oov_token= '<OOV>')

tokenizer.fit_on_texts(Sentence)

word_index = tokenizer.word_index


print(word_index)

sequences = tokenizer.texts_to_sequences(Sentence)
print(sequences)

padded = pad_sequences(sequences)
print(padded)